words = [
    "accessors",
    "agpl",
    "attw",
    "bundler",
    "cjs",
    "cwd",
    "esm",
    "execa",
    "jsdocs",
    "pathe",
    "tempy",
    "transpiling",
    "tsc",
    "tsdoc",
    "vitest",
    "zod",
    "zshy",
]
