words = [
  "accessors",
  "agpl",
  "attw",
  "bundler",
  "cjs",
  "cwd",
  "esm",
  "execa",
  "hcaptcha",
  "jsdocs",
  "oxfmt",
  "oxlint",
  "pathe",
  "tempy",
  "transpiling",
  "tsc",
  "tsdoc",
  "vitest",
  "zod",
  "zshy",
]
